from django.urls import path

from projects.views import (
    ClientCreateView,
    ClientListView,
    DocumentDownloadView,
    DocumentListView,
    FileTransferListView,
    GovernmentRecordListView,
    GovernmentRecordCreateView,
    MunicipalityActivityCreateView,
    MunicipalityActivityListView,
    PaymentCreateView,
    PaymentListView,
    PhysicalFileTransferCreateView,
    ProjectCommentCreateView,
    ProjectCreateView,
    ProjectDetailView,
    ProjectDocumentUploadView,
    ProjectListView,
    ProjectPublicView,
    ProjectQRCodeView,
    ProjectStageAdvanceView,
    SiteVisitCreateView,
    SiteVisitListView,
    TaskCreateView,
    TaskListView,
)


urlpatterns = [
    path("projects/", ProjectListView.as_view(), name="project-list"),
    path("projects/new/", ProjectCreateView.as_view(), name="project-create"),
    path("projects/<int:pk>/", ProjectDetailView.as_view(), name="project-detail"),
    path("projects/<int:pk>/stage/", ProjectStageAdvanceView.as_view(), name="project-stage-advance"),
    path("projects/<int:pk>/documents/upload/", ProjectDocumentUploadView.as_view(), name="project-document-upload"),
    path("projects/<int:pk>/tasks/new/", TaskCreateView.as_view(), name="project-task-create"),
    path("projects/<int:pk>/file-transfer/", PhysicalFileTransferCreateView.as_view(), name="project-file-transfer-create"),
    path("projects/<int:pk>/site-visit/", SiteVisitCreateView.as_view(), name="project-site-visit-create"),
    path("projects/<int:pk>/government-record/", GovernmentRecordCreateView.as_view(), name="project-government-record-create"),
    path("projects/<int:pk>/municipality-activity/", MunicipalityActivityCreateView.as_view(), name="project-municipality-activity-create"),
    path("projects/<int:pk>/payment/", PaymentCreateView.as_view(), name="project-payment-create"),
    path("projects/<int:pk>/comment/", ProjectCommentCreateView.as_view(), name="project-comment-create"),
    path("documents/<int:pk>/download/", DocumentDownloadView.as_view(), name="document-download"),
    path("projects/<int:pk>/qr.png", ProjectQRCodeView.as_view(), name="project-qr-image"),
    path("clients/", ClientListView.as_view(), name="clients"),
    path("clients/new/", ClientCreateView.as_view(), name="client-create"),
    path("tasks/", TaskListView.as_view(), name="tasks"),
    path("documents/", DocumentListView.as_view(), name="documents"),
    path("file-register/", FileTransferListView.as_view(), name="file-register"),
    path("site-visits/", SiteVisitListView.as_view(), name="site-visits"),
    path("government-records/", GovernmentRecordListView.as_view(), name="government-records"),
    path("municipality-tracking/", MunicipalityActivityListView.as_view(), name="municipality-tracking"),
    path("payments/", PaymentListView.as_view(), name="payments"),
    path("p/<str:token>/", ProjectPublicView.as_view(), name="project-public"),
]
