# Generated by Django 5.2.8 on 2026-09-05 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NumberingScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prefix', models.CharField(default='GEC', max_length=20)),
                ('service_code', models.CharField(max_length=20)),
                ('year_label', models.CharField(default='2083', max_length=8)),
                ('sequence_width', models.PositiveSmallIntegerField(default=4)),
                ('next_sequence', models.PositiveIntegerField(default=1)),
                ('separator', models.CharField(default='-', max_length=5)),
                ('format_template', models.CharField(default='{prefix}-{service_code}-{year_label}-{sequence:04d}', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('service_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='numbering_scheme', to='workflows.servicetype')),
            ],
            options={
                'ordering': ['service_type__name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('service_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_categories', to='workflows.servicetype')),
            ],
            options={
                'ordering': ['order', 'name'],
                'unique_together': {('code', 'service_type')},
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('required', models.BooleanField(default=True)),
                ('allow_exception', models.BooleanField(default=True)),
                ('must_be_seen_original', models.BooleanField(default=True)),
                ('must_be_scanned', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_templates', to='workflows.documentcategory')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_templates', to='workflows.servicetype')),
            ],
            options={
                'ordering': ['service_type__name', 'order', 'name'],
                'unique_together': {('service_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowStageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('default_status', models.CharField(choices=[('New', 'New'), ('Documents Pending', 'Documents Pending'), ('Documents Verification', 'Documents Verification'), ('Ready for Online Entry', 'Ready for Online Entry'), ('Plan Preparation', 'Plan Preparation'), ('Waiting for Client Approval', 'Waiting for Client Approval'), ('Waiting for Ward', 'Waiting for Ward'), ('Structural Work', 'Structural Work'), ('Online Processing', 'Online Processing'), ('Ready for Municipality', 'Ready for Municipality'), ('At Municipality', 'At Municipality'), ('Correction Required', 'Correction Required'), ('Approved', 'Approved'), ('Delivered', 'Delivered'), ('Payment Pending', 'Payment Pending'), ('Completed', 'Completed'), ('Archived', 'Archived'), ('Cancelled', 'Cancelled'), ('On Hold', 'On Hold')], default='New', max_length=64)),
                ('wait_type', models.CharField(choices=[('internal', 'Internal'), ('client', 'Waiting for client'), ('ward', 'Waiting for ward'), ('municipality', 'Waiting for municipality'), ('employee', 'Waiting for employee'), ('payment', 'Waiting for payment')], default='internal', max_length=20)),
                ('responsible_role_hint', models.CharField(blank=True, max_length=120)),
                ('due_days_default', models.PositiveIntegerField(default=3)),
                ('requires_document_completion', models.BooleanField(default=True)),
                ('is_start', models.BooleanField(default=False)),
                ('is_terminal', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_stages', to='workflows.servicetype')),
            ],
            options={
                'ordering': ['service_type__name', 'order', 'name'],
                'unique_together': {('service_type', 'code')},
            },
        ),
    ]
