# Generated by Django 5.2.8 on 2026-09-09 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def assign_existing_users_to_garima(apps, schema_editor):
    Company = apps.get_model("accounts", "Company")
    User = apps.get_model("accounts", "User")
    garima, _ = Company.objects.get_or_create(
        slug="garima-engineering-consultancy",
        defaults={"name": "Garima Engineering Consultancy"},
    )
    User.objects.filter(company__isnull=True).update(company=garima, company_role="admin")
    User.objects.filter(is_superuser=True).update(is_platform_admin=True)


def unassign_existing_users(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.update(company=None, is_platform_admin=False)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_role',
            field=models.CharField(choices=[('admin', 'Admin'), ('engineer', 'Engineer'), ('valuator', 'Valuator')], default='engineer', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='is_platform_admin',
            field=models.BooleanField(default=False, help_text='Allows access to platform-wide company administration. Keep this separate from company roles.'),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company-logos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.company'),
        ),
        migrations.RunPython(assign_existing_users_to_garima, unassign_existing_users),
    ]
