# Generated by Django 5.2.8 on 2026-09-13 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_access_records(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    PlatformRole = apps.get_model("accounts", "PlatformRole")
    Membership = apps.get_model("accounts", "OrganizationMembership")
    for user in User.objects.select_related("company").all():
        if user.is_platform_admin or user.is_superuser:
            PlatformRole.objects.get_or_create(user_id=user.pk, defaults={"role": "super_admin"})
        if user.company_id:
            Membership.objects.get_or_create(
                user_id=user.pk,
                organization_id=user.company_id,
                defaults={"role": "admin" if user.company_role == "admin" else "engineer"},
            )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_company_role_user_is_platform_admin_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin')], default='super_admin', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='platform_role', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('engineer', 'Engineer'), ('staff', 'Staff')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='accounts.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['organization__name'],
                'constraints': [models.UniqueConstraint(fields=('user', 'organization'), name='unique_active_org_membership')],
            },
        ),
        migrations.RunPython(backfill_access_records, migrations.RunPython.noop),
    ]
