# Generated by Django 5.2.8 on 2026-09-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_platformrole_organizationmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Require a private password to be set after a Super Admin provisions this account.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company_role',
            field=models.CharField(choices=[('admin', 'Admin'), ('engineer', 'Engineer'), ('valuator', 'Valuator'), ('staff', 'Staff')], default='engineer', max_length=20),
        ),
    ]
