# Generated by Django 5.2.8 on 2026-09-20 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_must_change_password_alter_user_company_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('is_core', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('navigation_label', models.CharField(blank=True, max_length=120)),
                ('navigation_url_name', models.CharField(blank=True, max_length=120)),
                ('navigation_icon', models.CharField(blank=True, max_length=80)),
                ('navigation_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['navigation_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('code', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'organization categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RoleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='company',
            name='applied_template_version',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='company',
            name='country_code',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='company',
            name='language_code',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='company',
            name='organization_code',
            field=models.SlugField(blank=True, max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='company',
            name='provisioning_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('provisioning', 'Provisioning'), ('ready', 'Ready'), ('failed', 'Failed')], default='ready', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_identifier',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='company',
            name='timezone_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='ModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='accounts.moduledefinition')),
            ],
            options={
                'ordering': ['module__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#245a78', max_length=20)),
                ('accent_color', models.CharField(default='#3b82f6', max_length=20)),
                ('report_header', models.CharField(blank=True, max_length=255)),
                ('report_footer', models.CharField(blank=True, max_length=500)),
                ('date_format', models.CharField(default='Y-m-d', max_length=32)),
                ('number_format', models.CharField(default='international', max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='accounts.company')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='accounts.organizationcategory'),
        ),
        migrations.CreateModel(
            name='OrganizationRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='accounts.company')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='organization_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='accounts.organizationrole'),
        ),
        migrations.CreateModel(
            name='OrganizationRolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organizationrole')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.modulepermission')),
            ],
        ),
        migrations.AddField(
            model_name='organizationrole',
            name='permissions',
            field=models.ManyToManyField(related_name='organization_roles', through='accounts.OrganizationRolePermission', to='accounts.modulepermission'),
        ),
        migrations.AddField(
            model_name='organizationrole',
            name='source_template_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_roles', to='accounts.roletemplate'),
        ),
        migrations.CreateModel(
            name='RoleTemplatePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.modulepermission')),
                ('role_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.roletemplate')),
            ],
        ),
        migrations.AddField(
            model_name='roletemplate',
            name='permissions',
            field=models.ManyToManyField(related_name='role_templates', through='accounts.RoleTemplatePermission', to='accounts.modulepermission'),
        ),
        migrations.CreateModel(
            name='SystemTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(default='1.0', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='system_templates', to='accounts.organizationcategory')),
            ],
            options={
                'ordering': ['name', '-version'],
            },
        ),
        migrations.AddField(
            model_name='roletemplate',
            name='system_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_templates', to='accounts.systemtemplate'),
        ),
        migrations.AddField(
            model_name='company',
            name='system_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='accounts.systemtemplate'),
        ),
        migrations.CreateModel(
            name='TemplateDashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80)),
                ('title', models.CharField(max_length=160)),
                ('component_key', models.CharField(max_length=120)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dashboard_widgets', to='accounts.moduledefinition')),
                ('system_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_widgets', to='accounts.systemtemplate')),
            ],
            options={
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TemplateModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.BooleanField(default=False)),
                ('enabled_by_default', models.BooleanField(default=True)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template_modules', to='accounts.moduledefinition')),
                ('system_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_modules', to='accounts.systemtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=160)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('definition', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_templates', to='accounts.moduledefinition')),
                ('system_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_templates', to='accounts.systemtemplate')),
            ],
            options={
                'ordering': ['name', '-version'],
            },
        ),
        migrations.CreateModel(
            name='ModuleConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.CharField(blank=True, max_length=255)),
                ('conflicting_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicted_by', to='accounts.moduledefinition')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='accounts.moduledefinition')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('module', 'conflicting_module'), name='unique_module_conflict')],
            },
        ),
        migrations.CreateModel(
            name='ModuleDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.CharField(blank=True, max_length=255)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='accounts.moduledefinition')),
                ('required_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_by', to='accounts.moduledefinition')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('module', 'required_module'), name='unique_module_dependency')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('enabled_at', models.DateTimeField(auto_now_add=True)),
                ('enabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organization_installations', to='accounts.moduledefinition')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enabled_modules', to='accounts.company')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'module'), name='unique_organization_module')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('job_title', models.CharField(blank=True, max_length=120)),
                ('token_digest', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_organization_invitations', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='accounts.company')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='accounts.organizationrole')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'email', 'accepted_at'], name='accounts_or_organiz_c2bffd_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='organizationrolepermission',
            constraint=models.UniqueConstraint(fields=('organization_role', 'permission'), name='unique_organization_role_permission'),
        ),
        migrations.AddConstraint(
            model_name='organizationrole',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_organization_role_code'),
        ),
        migrations.AddConstraint(
            model_name='roletemplatepermission',
            constraint=models.UniqueConstraint(fields=('role_template', 'permission'), name='unique_role_template_permission'),
        ),
        migrations.AddConstraint(
            model_name='systemtemplate',
            constraint=models.UniqueConstraint(fields=('code', 'version'), name='unique_system_template_version'),
        ),
        migrations.AddConstraint(
            model_name='roletemplate',
            constraint=models.UniqueConstraint(fields=('system_template', 'code'), name='unique_template_role_code'),
        ),
        migrations.AddConstraint(
            model_name='templatedashboardwidget',
            constraint=models.UniqueConstraint(fields=('system_template', 'code'), name='unique_template_dashboard_widget'),
        ),
        migrations.AddConstraint(
            model_name='templatemodule',
            constraint=models.UniqueConstraint(fields=('system_template', 'module'), name='unique_template_module'),
        ),
        migrations.AddConstraint(
            model_name='workflowtemplate',
            constraint=models.UniqueConstraint(fields=('system_template', 'code', 'version'), name='unique_workflow_template_version'),
        ),
    ]
