# Generated by Django 5.2.8 on 2026-09-22 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_seed_organization_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='company',
            name='currency_code',
            field=models.CharField(default='NPR', max_length=3),
        ),
        migrations.AddField(
            model_name='company',
            name='date_format',
            field=models.CharField(default='Y-m-d', max_length=32),
        ),
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='company',
            name='province',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='company',
            name='registration_number',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name='TemplateNavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('url_name', models.CharField(max_length=120)),
                ('icon', models.CharField(blank=True, max_length=80)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='navigation_items', to='accounts.moduledefinition')),
                ('required_permission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='navigation_items', to='accounts.modulepermission')),
                ('system_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navigation_items', to='accounts.systemtemplate')),
            ],
            options={
                'ordering': ['display_order', 'label'],
                'constraints': [models.UniqueConstraint(fields=('system_template', 'url_name'), name='unique_template_navigation_url')],
            },
        ),
    ]
