# Generated by Django 5.2.8 on 2026-09-24 06:23

import django.core.validators
import django.db.models.deletion
import professional_services.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0016_seed_professional_services_catalog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True)),
                ('default_duration_days', models.PositiveIntegerField(blank=True, null=True)),
                ('default_billing_method', models.CharField(choices=[('fixed', 'Fixed Price'), ('hourly', 'Hourly / Time and Materials'), ('milestone', 'Milestone'), ('retainer', 'Retainer'), ('internal', 'Non-billable / Internal')], default='fixed', max_length=20)),
                ('default_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('default_deliverables', models.TextField(blank=True)),
                ('responsible_department', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.company')),
            ],
            options={
                'ordering': ['name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('client_type', models.CharField(blank=True, max_length=80)),
                ('contact_person', models.CharField(blank=True, max_length=160)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('address', models.TextField(blank=True)),
                ('industry', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('prospective', 'Prospective'), ('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='prospective', max_length=20)),
                ('billing_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('account_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ps_clients', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.company')),
                ('services_used', models.ManyToManyField(blank=True, related_name='clients', to='professional_services.professionalservice')),
            ],
            options={
                'ordering': ['name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(default=professional_services.models.engagement_number, max_length=50)),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('billing_method', models.CharField(choices=[('fixed', 'Fixed Price'), ('hourly', 'Hourly / Time and Materials'), ('milestone', 'Milestone'), ('retainer', 'Retainer'), ('internal', 'Non-billable / Internal')], default='fixed', max_length=20)),
                ('contract_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('billing_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('progress', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('proposed', 'Proposed'), ('approved', 'Approved'), ('active', 'Active'), ('on_hold', 'On Hold'), ('awaiting_client', 'Awaiting Client'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('account_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ps_accounts', to=settings.AUTH_USER_MODEL)),
                ('assigned_team', models.ManyToManyField(blank=True, related_name='ps_engagements', to=settings.AUTH_USER_MODEL)),
                ('engagement_manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ps_managed_engagements', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.company')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='engagements', to='professional_services.professionalclient')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='engagements', to='professional_services.professionalservice')),
            ],
            options={
                'ordering': ['-updated_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='professional_settings', to='accounts.company')),
            ],
        ),
        migrations.AddIndex(
            model_name='professionalservice',
            index=models.Index(fields=['organization', 'status'], name='professiona_organiz_547501_idx'),
        ),
        migrations.AddConstraint(
            model_name='professionalservice',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='ps_unique_service_code'),
        ),
        migrations.AddConstraint(
            model_name='professionalservice',
            constraint=models.CheckConstraint(condition=models.Q(('default_rate__gte', 0), ('default_rate__isnull', True), _connector='OR'), name='ps_service_rate_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='professionalclient',
            index=models.Index(fields=['organization', 'status'], name='professiona_organiz_dc1500_idx'),
        ),
        migrations.AddConstraint(
            model_name='professionalclient',
            constraint=models.CheckConstraint(condition=models.Q(('billing_rate__gte', 0), ('billing_rate__isnull', True), _connector='OR'), name='ps_client_rate_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='engagement',
            index=models.Index(fields=['organization', 'status'], name='professiona_organiz_a9ef2f_idx'),
        ),
        migrations.AddIndex(
            model_name='engagement',
            index=models.Index(fields=['organization', 'due_date'], name='professiona_organiz_ce614e_idx'),
        ),
        migrations.AddConstraint(
            model_name='engagement',
            constraint=models.UniqueConstraint(fields=('organization', 'number'), name='ps_unique_engagement_number'),
        ),
        migrations.AddConstraint(
            model_name='engagement',
            constraint=models.CheckConstraint(condition=models.Q(('progress__lte', 100)), name='ps_progress_at_most_100'),
        ),
        migrations.AddConstraint(
            model_name='engagement',
            constraint=models.CheckConstraint(condition=models.Q(('due_date__gte', models.F('start_date')), ('start_date__isnull', True), ('due_date__isnull', True), _connector='OR'), name='ps_engagement_date_order'),
        ),
        migrations.AddConstraint(
            model_name='engagement',
            constraint=models.CheckConstraint(condition=models.Q(('billing_rate__gte', 0), ('billing_rate__isnull', True), _connector='OR'), name='ps_engagement_rate_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='engagement',
            constraint=models.CheckConstraint(condition=models.Q(('contract_amount__gte', 0), ('contract_amount__isnull', True), _connector='OR'), name='ps_contract_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='professionalsettings',
            constraint=models.CheckConstraint(condition=models.Q(('default_rate__gte', 0), ('default_rate__isnull', True), _connector='OR'), name='ps_settings_rate_nonnegative'),
        ),
    ]
